// src/ssr/prefetch.ts
// SSR-safe — all document access is guarded with typeof document !== 'undefined'.

/**
 * A single route entry from the prefetch manifest.
 * @internal
 */
interface PrefetchRouteEntry {
  readonly pattern: string;
  readonly chunks: readonly string[];
  readonly css: readonly string[];
}

/**
 * Shape of `prefetch-manifest.json` generated by `snapshotSsr()`.
 * @internal
 */
interface PrefetchManifestShape {
  readonly routes: readonly PrefetchRouteEntry[];
}

// ── Module-level manifest promise ─────────────────────────────────────────────
// This is a lazy-initialized Promise — not mutable runtime state. The manifest
// is a static build artifact; it never changes for the lifetime of the page.
// Multiple callers share the same in-flight fetch, and the resolved value is
// stored once. This is safe and intentional (no cross-request contamination in
// a browser context). Rule 3 exception: idempotent build artifact cache.

let manifestPromise: Promise<PrefetchManifestShape> | null = null;

/**
 * Fetch and parse the prefetch manifest exactly once per page load.
 * Subsequent calls return the cached Promise.
 * @internal
 */
function loadManifest(): Promise<PrefetchManifestShape> {
  if (manifestPromise) return manifestPromise;

  manifestPromise = fetch("/prefetch-manifest.json")
    .then((res) => {
      if (!res.ok) {
        // No manifest — return an empty one so the hook is a no-op.
        return { routes: [] } as PrefetchManifestShape;
      }
      return res.json() as Promise<PrefetchManifestShape>;
    })
    .catch(() => ({ routes: [] } as PrefetchManifestShape));

  return manifestPromise;
}

// ── Prefetched-chunks tracker ─────────────────────────────────────────────────
// Module-level Set of already-injected URLs. Browser-only DOM state — no
// cross-request contamination is possible in a browser. Re-injecting the same
// <link> would be a no-op from the browser's perspective, but deduplication
// avoids polluting the <head>.

const prefetchedUrls = new Set<string>();

/**
 * Convert a `:param` pattern to a RegExp for URL matching.
 *
 * - `:slug`  → matches a single segment
 * - `:rest*` → matches one or more segments (catch-all)
 *
 * @param pattern - URL pattern in `:param` syntax, e.g. `/posts/:slug`.
 * @returns A RegExp that matches paths conforming to the pattern.
 * @internal
 */
function patternToRegex(pattern: string): RegExp {
  const escaped = pattern
    // Catch-all: :name* → match remaining path including slashes
    .replace(/:([a-zA-Z_][a-zA-Z0-9_]*)\*/g, "([^?#]+)")
    // Named param: :name → match a single segment
    .replace(/:([a-zA-Z_][a-zA-Z0-9_]*)/g, "([^/?#]+)");

  return new RegExp(`^${escaped}(?:\\?.*)?$`);
}

/**
 * Find the manifest entry whose pattern matches a given URL path.
 * @internal
 */
function matchRoute(
  routes: readonly PrefetchRouteEntry[],
  urlPath: string,
): PrefetchRouteEntry | null {
  for (const route of routes) {
    if (patternToRegex(route.pattern).test(urlPath)) return route;
  }
  return null;
}

/**
 * Inject a single `<link rel="prefetch">` tag into `document.head`.
 * No-op if the URL has already been injected this session.
 * @internal
 */
function injectPrefetchLink(href: string, as: "script" | "style"): void {
  if (prefetchedUrls.has(href)) return;
  prefetchedUrls.add(href);

  const link = document.createElement("link");
  link.rel = "prefetch";
  link.as = as;
  link.href = href.startsWith("/") ? href : `/${href}`;
  document.head.appendChild(link);
}

/**
 * Returns a callback that prefetches the JS chunks and CSS files for a given
 * URL path by injecting `<link rel="prefetch">` tags into `document.head`.
 *
 * The prefetch manifest (`/prefetch-manifest.json`) is loaded once per page
 * load and cached. Duplicate prefetch injections for the same URL are suppressed.
 *
 * Safe to call during SSR — all `document` access is guarded. The returned
 * function is a no-op on the server.
 *
 * @returns A stable callback `(path: string) => void`. Call it with the URL path
 *   to prefetch (e.g. `"/posts/my-slug"`).
 *
 * @example
 * ```tsx
 * function MyLink() {
 *   const prefetch = usePrefetchRoute();
 *   return (
 *     <a href="/posts" onMouseEnter={() => prefetch('/posts')}>
 *       Posts
 *     </a>
 *   );
 * }
 * ```
 */
export function usePrefetchRoute(): (path: string) => void {
  // SSR guard — return a no-op function when running outside the browser.
  if (typeof document === "undefined") {
    return () => {};
  }

  return (urlPath: string) => {
    void loadManifest().then((manifest) => {
      const route = matchRoute(manifest.routes, urlPath);
      if (!route) return;

      for (const chunk of route.chunks) {
        injectPrefetchLink(chunk, "script");
      }
      for (const css of route.css) {
        injectPrefetchLink(css, "style");
      }
    });
  };
}
