import { writeFileSync } from "node:fs";
import path from "node:path";
import {
  collectRegisteredManifestComponents,
  type ManifestComponentRecord,
} from "../docs/component-inventory.ts";
import { ensureDir, repoPath } from "../docs/_common.ts";

function toPascalCase(value: string): string {
  const words = value
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);

  const candidate = words
    .map((word) => `${word.charAt(0).toUpperCase()}${word.slice(1)}`)
    .join("");

  return /^[0-9]/.test(candidate) ? `Component${candidate}` : candidate;
}

function uniqueStoryName(
  component: ManifestComponentRecord,
  used: Set<string>,
): string {
  const base = toPascalCase(component.type);
  if (!used.has(base)) {
    used.add(base);
    return base;
  }

  const withDomain = `${toPascalCase(component.domain)}${base}`;
  if (!used.has(withDomain)) {
    used.add(withDomain);
    return withDomain;
  }

  let index = 2;
  while (used.has(`${withDomain}${index}`)) {
    index += 1;
  }

  const name = `${withDomain}${index}`;
  used.add(name);
  return name;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

const components = collectRegisteredManifestComponents();
const usedStoryNames = new Set<string>();
const storyRecords = components.map((component) => ({
  ...component,
  storyName: uniqueStoryName(component, usedStoryNames),
}));

const outputFile = repoPath(
  "src",
  "ui",
  "components",
  "__stories__",
  "generated-components.stories.tsx",
);

const componentMeta = storyRecords.map((component) => ({
  type: component.type,
  domain: component.domain,
  path: component.relativeDir,
}));

const lines: string[] = [];
lines.push("/* This file is generated by scripts/storybook/generate-component-stories.ts. */");
lines.push("/* Do not edit manually. */");
lines.push("");
lines.push("import type { Meta, StoryObj } from \"@storybook/react-vite\";");
lines.push("import {");
lines.push("  ComponentCatalogFrame,");
lines.push("  ComponentStoryFrame,");
lines.push("  getComponentStoryArgs,");
lines.push("  type ComponentStoryMeta,");
lines.push("} from \"./component-story-frame\";");
lines.push("");
lines.push("const COMPONENTS = [");
for (const component of componentMeta) {
  lines.push(
    `  { type: ${quote(component.type)}, domain: ${quote(component.domain)}, path: ${quote(component.path)} },`,
  );
}
lines.push("] as const satisfies readonly ComponentStoryMeta[];");
lines.push("");
lines.push("const meta = {");
lines.push("  title: \"Snapshot/Generated Components\",");
lines.push("  component: ComponentStoryFrame,");
lines.push("  render: (args) => <ComponentStoryFrame {...args} />,");
lines.push("  parameters: {");
lines.push("    controls: { expanded: true },");
lines.push("  },");
lines.push("  argTypes: {");
lines.push("    componentType: { control: false },");
lines.push("    fixtureName: { control: \"text\" },");
lines.push("    maxWidth: { control: \"text\" },");
lines.push("    config: { control: \"object\" },");
lines.push("  },");
lines.push("} satisfies Meta<typeof ComponentStoryFrame>;");
lines.push("");
lines.push("export default meta;");
lines.push("");
lines.push("type Story = StoryObj<typeof meta>;");
lines.push("");
lines.push("export const AllComponents: Story = {");
lines.push("  name: \"All components\",");
lines.push("  args: getComponentStoryArgs(COMPONENTS[0].type),");
lines.push("  render: () => <ComponentCatalogFrame components={COMPONENTS} />,");
lines.push("  parameters: {");
lines.push("    controls: { disable: true },");
lines.push("  },");
lines.push("};");
lines.push("");

for (const component of storyRecords) {
  lines.push(`export const ${component.storyName}: Story = {`);
  lines.push(`  name: ${quote(component.type)},`);
  lines.push(`  args: getComponentStoryArgs(${quote(component.type)}),`);
  lines.push("};");
  lines.push("");
}

ensureDir(outputFile);
writeFileSync(outputFile, `${lines.join("\n").trim()}\n`, "utf8");

const relativeOutput = path.relative(repoPath(), outputFile).replace(/\\/g, "/");
console.log(
  `[storybook:generate] Wrote ${storyRecords.length} component stories to ${relativeOutput}.`,
);
