/* This file is generated by scripts/storybook/generate-component-stories.ts. */
/* Do not edit manually. */

import type { Meta, StoryObj } from "@storybook/react-vite";
import {
  ComponentCatalogFrame,
  ComponentStoryFrame,
  getComponentStoryArgs,
  type ComponentStoryMeta,
} from "./component-story-frame";

const COMPONENTS = [
  { type: "accordion", domain: "navigation", path: "navigation/accordion" },
  { type: "alert", domain: "data", path: "data/alert" },
  { type: "audit-log", domain: "workflow", path: "workflow/audit-log" },
  { type: "auto-form", domain: "forms", path: "forms/auto-form" },
  { type: "avatar", domain: "data", path: "data/avatar" },
  { type: "avatar-group", domain: "data", path: "data/avatar-group" },
  { type: "badge", domain: "data", path: "data/badge" },
  { type: "banner", domain: "content", path: "content/banner" },
  { type: "box", domain: "layout", path: "layout/box" },
  { type: "breadcrumb", domain: "navigation", path: "navigation/breadcrumb" },
  { type: "button", domain: "forms", path: "forms/button" },
  { type: "calendar", domain: "workflow", path: "workflow/calendar" },
  { type: "card", domain: "layout", path: "layout/card" },
  { type: "carousel", domain: "media", path: "media/carousel" },
  { type: "chart", domain: "data", path: "data/chart" },
  { type: "chat-window", domain: "communication", path: "communication/chat-window" },
  { type: "code", domain: "content", path: "content/code" },
  { type: "code-block", domain: "content", path: "content/code-block" },
  { type: "collapsible", domain: "layout", path: "layout/collapsible" },
  { type: "color-picker", domain: "forms", path: "forms/color-picker" },
  { type: "column", domain: "layout", path: "layout/column" },
  { type: "command-palette", domain: "overlay", path: "overlay/command-palette" },
  { type: "comment-section", domain: "communication", path: "communication/comment-section" },
  { type: "compare-view", domain: "content", path: "content/compare-view" },
  { type: "component-group", domain: "_base", path: "_base/component-group" },
  { type: "confirm-dialog", domain: "overlay", path: "overlay/confirm-dialog" },
  { type: "container", domain: "layout", path: "layout/container" },
  { type: "context-menu", domain: "overlay", path: "overlay/context-menu" },
  { type: "data-table", domain: "data", path: "data/data-table" },
  { type: "date-picker", domain: "forms", path: "forms/date-picker" },
  { type: "detail-card", domain: "data", path: "data/detail-card" },
  { type: "divider", domain: "primitives", path: "primitives/divider" },
  { type: "drawer", domain: "overlay", path: "overlay/drawer" },
  { type: "dropdown-menu", domain: "overlay", path: "overlay/dropdown-menu" },
  { type: "embed", domain: "media", path: "media/embed" },
  { type: "emoji-picker", domain: "communication", path: "communication/emoji-picker" },
  { type: "empty-state", domain: "data", path: "data/empty-state" },
  { type: "entity-picker", domain: "data", path: "data/entity-picker" },
  { type: "error-page", domain: "feedback", path: "feedback/default-error" },
  { type: "favorite-button", domain: "data", path: "data/favorite-button" },
  { type: "feed", domain: "data", path: "data/feed" },
  { type: "file-uploader", domain: "content", path: "content/file-uploader" },
  { type: "filter-bar", domain: "data", path: "data/filter-bar" },
  { type: "floating-menu", domain: "primitives", path: "primitives/floating-menu" },
  { type: "form", domain: "forms", path: "forms/auto-form" },
  { type: "gif-picker", domain: "communication", path: "communication/gif-picker" },
  { type: "grid", domain: "layout", path: "layout/grid" },
  { type: "heading", domain: "content", path: "content/heading" },
  { type: "highlighted-text", domain: "data", path: "data/highlighted-text" },
  { type: "hover-card", domain: "overlay", path: "overlay/hover-card" },
  { type: "icon-button", domain: "forms", path: "forms/icon-button" },
  { type: "image", domain: "media", path: "media/image" },
  { type: "inline-edit", domain: "forms", path: "forms/inline-edit" },
  { type: "input", domain: "forms", path: "forms/input" },
  { type: "kanban", domain: "workflow", path: "workflow/kanban" },
  { type: "link", domain: "primitives", path: "primitives/link" },
  { type: "link-embed", domain: "content", path: "content/link-embed" },
  { type: "list", domain: "data", path: "data/list" },
  { type: "location-input", domain: "forms", path: "forms/location-input" },
  { type: "markdown", domain: "content", path: "content/markdown" },
  { type: "message-thread", domain: "communication", path: "communication/message-thread" },
  { type: "modal", domain: "overlay", path: "overlay/modal" },
  { type: "multi-select", domain: "forms", path: "forms/multi-select" },
  { type: "nav-dropdown", domain: "layout", path: "layout/nav-dropdown" },
  { type: "nav-link", domain: "layout", path: "layout/nav-link" },
  { type: "nav-logo", domain: "layout", path: "layout/nav-logo" },
  { type: "nav-search", domain: "layout", path: "layout/nav-search" },
  { type: "nav-section", domain: "layout", path: "layout/nav-section" },
  { type: "nav-user-menu", domain: "layout", path: "layout/nav-user-menu" },
  { type: "not-found", domain: "feedback", path: "feedback/default-not-found" },
  { type: "notification-bell", domain: "data", path: "data/notification-bell" },
  { type: "notification-feed", domain: "workflow", path: "workflow/notification-feed" },
  { type: "oauth-buttons", domain: "primitives", path: "primitives/oauth-buttons" },
  { type: "offline-banner", domain: "feedback", path: "feedback/default-offline" },
  { type: "outlet", domain: "layout", path: "layout/outlet" },
  { type: "passkey-button", domain: "primitives", path: "primitives/passkey-button" },
  { type: "popover", domain: "overlay", path: "overlay/popover" },
  { type: "presence-indicator", domain: "communication", path: "communication/presence-indicator" },
  { type: "pricing-table", domain: "commerce", path: "commerce/pricing-table" },
  { type: "progress", domain: "data", path: "data/progress" },
  { type: "quick-add", domain: "forms", path: "forms/quick-add" },
  { type: "reaction-bar", domain: "communication", path: "communication/reaction-bar" },
  { type: "rich-input", domain: "content", path: "content/rich-input" },
  { type: "rich-text-editor", domain: "content", path: "content/rich-text-editor" },
  { type: "row", domain: "layout", path: "layout/row" },
  { type: "save-indicator", domain: "data", path: "data/save-indicator" },
  { type: "scroll-area", domain: "data", path: "data/scroll-area" },
  { type: "section", domain: "layout", path: "layout/section" },
  { type: "select", domain: "forms", path: "forms/select" },
  { type: "separator", domain: "data", path: "data/separator" },
  { type: "skeleton", domain: "data", path: "data/skeleton" },
  { type: "slider", domain: "forms", path: "forms/slider" },
  { type: "spacer", domain: "layout", path: "layout/spacer" },
  { type: "spinner", domain: "feedback", path: "feedback/default-loading" },
  { type: "split-pane", domain: "layout", path: "layout/split-pane" },
  { type: "stack", domain: "primitives", path: "primitives/stack" },
  { type: "stat-card", domain: "data", path: "data/stat-card" },
  { type: "stepper", domain: "navigation", path: "navigation/stepper" },
  { type: "switch", domain: "forms", path: "forms/switch" },
  { type: "tabs", domain: "navigation", path: "navigation/tabs" },
  { type: "tag-selector", domain: "forms", path: "forms/tag-selector" },
  { type: "text", domain: "primitives", path: "primitives/text" },
  { type: "textarea", domain: "forms", path: "forms/textarea" },
  { type: "timeline", domain: "content", path: "content/timeline" },
  { type: "toggle", domain: "forms", path: "forms/toggle" },
  { type: "toggle-group", domain: "forms", path: "forms/toggle-group" },
  { type: "tooltip", domain: "data", path: "data/tooltip" },
  { type: "tree-view", domain: "navigation", path: "navigation/tree-view" },
  { type: "typing-indicator", domain: "communication", path: "communication/typing-indicator" },
  { type: "video", domain: "media", path: "media/video" },
  { type: "vote", domain: "data", path: "data/vote" },
  { type: "wizard", domain: "forms", path: "forms/wizard" },
] as const satisfies readonly ComponentStoryMeta[];

const meta = {
  title: "Components/Config-Driven",
  component: ComponentStoryFrame,
  render: (args) => <ComponentStoryFrame {...args} />,
  parameters: {
    controls: { expanded: true },
  },
  argTypes: {
    componentType: { control: false },
    fixtureName: { control: "text" },
    maxWidth: { control: "text" },
    config: { control: "object" },
  },
} satisfies Meta<typeof ComponentStoryFrame>;

export default meta;

type Story = StoryObj<typeof meta>;

export const AllComponents: Story = {
  name: "All components",
  args: getComponentStoryArgs(COMPONENTS[0].type),
  render: () => <ComponentCatalogFrame components={COMPONENTS} />,
  parameters: {
    controls: { disable: true },
  },
};

export const Accordion: Story = {
  name: "accordion",
  args: getComponentStoryArgs("accordion"),
};

export const Alert: Story = {
  name: "alert",
  args: getComponentStoryArgs("alert"),
};

export const AuditLog: Story = {
  name: "audit-log",
  args: getComponentStoryArgs("audit-log"),
};

export const AutoForm: Story = {
  name: "auto-form",
  args: getComponentStoryArgs("auto-form"),
};

export const Avatar: Story = {
  name: "avatar",
  args: getComponentStoryArgs("avatar"),
};

export const AvatarGroup: Story = {
  name: "avatar-group",
  args: getComponentStoryArgs("avatar-group"),
};

export const Badge: Story = {
  name: "badge",
  args: getComponentStoryArgs("badge"),
};

export const Banner: Story = {
  name: "banner",
  args: getComponentStoryArgs("banner"),
};

export const Box: Story = {
  name: "box",
  args: getComponentStoryArgs("box"),
};

export const Breadcrumb: Story = {
  name: "breadcrumb",
  args: getComponentStoryArgs("breadcrumb"),
};

export const Button: Story = {
  name: "button",
  args: getComponentStoryArgs("button"),
};

export const Calendar: Story = {
  name: "calendar",
  args: getComponentStoryArgs("calendar"),
};

export const Card: Story = {
  name: "card",
  args: getComponentStoryArgs("card"),
};

export const Carousel: Story = {
  name: "carousel",
  args: getComponentStoryArgs("carousel"),
};

export const Chart: Story = {
  name: "chart",
  args: getComponentStoryArgs("chart"),
};

export const ChatWindow: Story = {
  name: "chat-window",
  args: getComponentStoryArgs("chat-window"),
};

export const Code: Story = {
  name: "code",
  args: getComponentStoryArgs("code"),
};

export const CodeBlock: Story = {
  name: "code-block",
  args: getComponentStoryArgs("code-block"),
};

export const Collapsible: Story = {
  name: "collapsible",
  args: getComponentStoryArgs("collapsible"),
};

export const ColorPicker: Story = {
  name: "color-picker",
  args: getComponentStoryArgs("color-picker"),
};

export const Column: Story = {
  name: "column",
  args: getComponentStoryArgs("column"),
};

export const CommandPalette: Story = {
  name: "command-palette",
  args: getComponentStoryArgs("command-palette"),
};

export const CommentSection: Story = {
  name: "comment-section",
  args: getComponentStoryArgs("comment-section"),
};

export const CompareView: Story = {
  name: "compare-view",
  args: getComponentStoryArgs("compare-view"),
};

export const ComponentGroup: Story = {
  name: "component-group",
  args: getComponentStoryArgs("component-group"),
};

export const ConfirmDialog: Story = {
  name: "confirm-dialog",
  args: getComponentStoryArgs("confirm-dialog"),
};

export const Container: Story = {
  name: "container",
  args: getComponentStoryArgs("container"),
};

export const ContextMenu: Story = {
  name: "context-menu",
  args: getComponentStoryArgs("context-menu"),
};

export const DataTable: Story = {
  name: "data-table",
  args: getComponentStoryArgs("data-table"),
};

export const DatePicker: Story = {
  name: "date-picker",
  args: getComponentStoryArgs("date-picker"),
};

export const DetailCard: Story = {
  name: "detail-card",
  args: getComponentStoryArgs("detail-card"),
};

export const Divider: Story = {
  name: "divider",
  args: getComponentStoryArgs("divider"),
};

export const Drawer: Story = {
  name: "drawer",
  args: getComponentStoryArgs("drawer"),
};

export const DropdownMenu: Story = {
  name: "dropdown-menu",
  args: getComponentStoryArgs("dropdown-menu"),
};

export const Embed: Story = {
  name: "embed",
  args: getComponentStoryArgs("embed"),
};

export const EmojiPicker: Story = {
  name: "emoji-picker",
  args: getComponentStoryArgs("emoji-picker"),
};

export const EmptyState: Story = {
  name: "empty-state",
  args: getComponentStoryArgs("empty-state"),
};

export const EntityPicker: Story = {
  name: "entity-picker",
  args: getComponentStoryArgs("entity-picker"),
};

export const ErrorPage: Story = {
  name: "error-page",
  args: getComponentStoryArgs("error-page"),
};

export const FavoriteButton: Story = {
  name: "favorite-button",
  args: getComponentStoryArgs("favorite-button"),
};

export const Feed: Story = {
  name: "feed",
  args: getComponentStoryArgs("feed"),
};

export const FileUploader: Story = {
  name: "file-uploader",
  args: getComponentStoryArgs("file-uploader"),
};

export const FilterBar: Story = {
  name: "filter-bar",
  args: getComponentStoryArgs("filter-bar"),
};

export const FloatingMenu: Story = {
  name: "floating-menu",
  args: getComponentStoryArgs("floating-menu"),
};

export const Form: Story = {
  name: "form",
  args: getComponentStoryArgs("form"),
};

export const GifPicker: Story = {
  name: "gif-picker",
  args: getComponentStoryArgs("gif-picker"),
};

export const Grid: Story = {
  name: "grid",
  args: getComponentStoryArgs("grid"),
};

export const Heading: Story = {
  name: "heading",
  args: getComponentStoryArgs("heading"),
};

export const HighlightedText: Story = {
  name: "highlighted-text",
  args: getComponentStoryArgs("highlighted-text"),
};

export const HoverCard: Story = {
  name: "hover-card",
  args: getComponentStoryArgs("hover-card"),
};

export const IconButton: Story = {
  name: "icon-button",
  args: getComponentStoryArgs("icon-button"),
};

export const Image: Story = {
  name: "image",
  args: getComponentStoryArgs("image"),
};

export const InlineEdit: Story = {
  name: "inline-edit",
  args: getComponentStoryArgs("inline-edit"),
};

export const Input: Story = {
  name: "input",
  args: getComponentStoryArgs("input"),
};

export const Kanban: Story = {
  name: "kanban",
  args: getComponentStoryArgs("kanban"),
};

export const Link: Story = {
  name: "link",
  args: getComponentStoryArgs("link"),
};

export const LinkEmbed: Story = {
  name: "link-embed",
  args: getComponentStoryArgs("link-embed"),
};

export const List: Story = {
  name: "list",
  args: getComponentStoryArgs("list"),
};

export const LocationInput: Story = {
  name: "location-input",
  args: getComponentStoryArgs("location-input"),
};

export const Markdown: Story = {
  name: "markdown",
  args: getComponentStoryArgs("markdown"),
};

export const MessageThread: Story = {
  name: "message-thread",
  args: getComponentStoryArgs("message-thread"),
};

export const Modal: Story = {
  name: "modal",
  args: getComponentStoryArgs("modal"),
};

export const MultiSelect: Story = {
  name: "multi-select",
  args: getComponentStoryArgs("multi-select"),
};

export const NavDropdown: Story = {
  name: "nav-dropdown",
  args: getComponentStoryArgs("nav-dropdown"),
};

export const NavLink: Story = {
  name: "nav-link",
  args: getComponentStoryArgs("nav-link"),
};

export const NavLogo: Story = {
  name: "nav-logo",
  args: getComponentStoryArgs("nav-logo"),
};

export const NavSearch: Story = {
  name: "nav-search",
  args: getComponentStoryArgs("nav-search"),
};

export const NavSection: Story = {
  name: "nav-section",
  args: getComponentStoryArgs("nav-section"),
};

export const NavUserMenu: Story = {
  name: "nav-user-menu",
  args: getComponentStoryArgs("nav-user-menu"),
};

export const NotFound: Story = {
  name: "not-found",
  args: getComponentStoryArgs("not-found"),
};

export const NotificationBell: Story = {
  name: "notification-bell",
  args: getComponentStoryArgs("notification-bell"),
};

export const NotificationFeed: Story = {
  name: "notification-feed",
  args: getComponentStoryArgs("notification-feed"),
};

export const OauthButtons: Story = {
  name: "oauth-buttons",
  args: getComponentStoryArgs("oauth-buttons"),
};

export const OfflineBanner: Story = {
  name: "offline-banner",
  args: getComponentStoryArgs("offline-banner"),
};

export const Outlet: Story = {
  name: "outlet",
  args: getComponentStoryArgs("outlet"),
};

export const PasskeyButton: Story = {
  name: "passkey-button",
  args: getComponentStoryArgs("passkey-button"),
};

export const Popover: Story = {
  name: "popover",
  args: getComponentStoryArgs("popover"),
};

export const PresenceIndicator: Story = {
  name: "presence-indicator",
  args: getComponentStoryArgs("presence-indicator"),
};

export const PricingTable: Story = {
  name: "pricing-table",
  args: getComponentStoryArgs("pricing-table"),
};

export const Progress: Story = {
  name: "progress",
  args: getComponentStoryArgs("progress"),
};

export const QuickAdd: Story = {
  name: "quick-add",
  args: getComponentStoryArgs("quick-add"),
};

export const ReactionBar: Story = {
  name: "reaction-bar",
  args: getComponentStoryArgs("reaction-bar"),
};

export const RichInput: Story = {
  name: "rich-input",
  args: getComponentStoryArgs("rich-input"),
};

export const RichTextEditor: Story = {
  name: "rich-text-editor",
  args: getComponentStoryArgs("rich-text-editor"),
};

export const Row: Story = {
  name: "row",
  args: getComponentStoryArgs("row"),
};

export const SaveIndicator: Story = {
  name: "save-indicator",
  args: getComponentStoryArgs("save-indicator"),
};

export const ScrollArea: Story = {
  name: "scroll-area",
  args: getComponentStoryArgs("scroll-area"),
};

export const Section: Story = {
  name: "section",
  args: getComponentStoryArgs("section"),
};

export const Select: Story = {
  name: "select",
  args: getComponentStoryArgs("select"),
};

export const Separator: Story = {
  name: "separator",
  args: getComponentStoryArgs("separator"),
};

export const Skeleton: Story = {
  name: "skeleton",
  args: getComponentStoryArgs("skeleton"),
};

export const Slider: Story = {
  name: "slider",
  args: getComponentStoryArgs("slider"),
};

export const Spacer: Story = {
  name: "spacer",
  args: getComponentStoryArgs("spacer"),
};

export const Spinner: Story = {
  name: "spinner",
  args: getComponentStoryArgs("spinner"),
};

export const SplitPane: Story = {
  name: "split-pane",
  args: getComponentStoryArgs("split-pane"),
};

export const Stack: Story = {
  name: "stack",
  args: getComponentStoryArgs("stack"),
};

export const StatCard: Story = {
  name: "stat-card",
  args: getComponentStoryArgs("stat-card"),
};

export const Stepper: Story = {
  name: "stepper",
  args: getComponentStoryArgs("stepper"),
};

export const Switch: Story = {
  name: "switch",
  args: getComponentStoryArgs("switch"),
};

export const Tabs: Story = {
  name: "tabs",
  args: getComponentStoryArgs("tabs"),
};

export const TagSelector: Story = {
  name: "tag-selector",
  args: getComponentStoryArgs("tag-selector"),
};

export const Text: Story = {
  name: "text",
  args: getComponentStoryArgs("text"),
};

export const Textarea: Story = {
  name: "textarea",
  args: getComponentStoryArgs("textarea"),
};

export const Timeline: Story = {
  name: "timeline",
  args: getComponentStoryArgs("timeline"),
};

export const Toggle: Story = {
  name: "toggle",
  args: getComponentStoryArgs("toggle"),
};

export const ToggleGroup: Story = {
  name: "toggle-group",
  args: getComponentStoryArgs("toggle-group"),
};

export const Tooltip: Story = {
  name: "tooltip",
  args: getComponentStoryArgs("tooltip"),
};

export const TreeView: Story = {
  name: "tree-view",
  args: getComponentStoryArgs("tree-view"),
};

export const TypingIndicator: Story = {
  name: "typing-indicator",
  args: getComponentStoryArgs("typing-indicator"),
};

export const Video: Story = {
  name: "video",
  args: getComponentStoryArgs("video"),
};

export const Vote: Story = {
  name: "vote",
  args: getComponentStoryArgs("vote"),
};

export const Wizard: Story = {
  name: "wizard",
  args: getComponentStoryArgs("wizard"),
};
